import { StyleSheet } from "react-native";

//Global Styles
export default StyleSheet.create({
  contentContainer: {
    height: "100%",
    backgroundColor: "white",
  },
  homeHeadContainer: {
    width: "100%",
    paddingTop: "20%",
    padding: 20,
  },
  homeHead: {
    marginLeft: 30,
    fontSize: 25,
    fontWeight: "bold",
    fontFamily: "Optima-Bold",
    paddingTop: "14%",
  },
  routeOptionContainer: {
    paddingHorizontal: 20,
    paddingBottom: 20,
    marginBottom: 0,
    zIndex: 3,
    height: "100%",
    width: "100%",
  },
  routeOption: {
    padding: 13,
    marginVertical: 10,
    backgroundColor: "#F3F3F3",
    height: 140,
    width: "100%",
    display: "flex",
    flexDirection: "row",
    borderRadius: 15,
  },
  imageCircle: {
    backgroundColor: "white",
    height: 115,
    width: 115,
    borderRadius: 100,
  },
  routeTextHeading: {
    marginLeft: 15,
    marginTop: 5,
    fontSize: 21,
    fontWeight: "bold",
    fontFamily: "Optima-Bold",
  },
  routeText: {
    width: "60%",
    marginLeft: 15,
    marginTop: 5,
  },
  routeTagFirst: {
    display: "flex",
    flexDirection: "row",
    marginLeft: 15,
    marginTop: 15,
  },
  routeTagSecond: {
    display: "flex",
    flexDirection: "row",
    marginBottom: 10,
    position: "absolute",
    top: "88%",
    left: "20%",
  },
  textContainer: {
    padding: 30,
    paddingTop: 0,
    position: "absolute",
    top: "35%",
    borderTopLeftRadius: "30%",
    borderTopRightRadius: "30%",
    marginTop: 0,
    backgroundColor: "white",
    zIndex: 3,
    height: "65%",
    width: "100%",
    flex: 1,
  },
  navigationContainer: {
    padding: 30,
    paddingTop: 0,
    position: "absolute",
    top: "65%",
    borderTopLeftRadius: "30%",
    borderTopRightRadius: "30%",
    marginTop: 0,
    backgroundColor: "white",
    zIndex: 3,
    height: "30%",
    width: "100%",
    flex: 1,
  },
  tagContainer: {
    display: "flex",
    flexDirection: "row",
    marginBottom: 6,
    marginTop: 12,
  },
  quizContainer: {
    width: "100%",
  },
  text: {
    fontSize: 16,
    fontFamily: "HelveticaNeue-Light",
    color: "#686868",
    flex: 1,
    paddingTop: 10,
  },
  heading: {
    fontSize: 25,
    fontWeight: "bold",
    fontFamily: "Optima-Bold",
    paddingTop: "5%",
  },
  question: {
    fontSize: 19,
    fontWeight: "bold",
    fontFamily: "Optima-Bold",
    paddingTop: "5%",
  },
  image: {
    width: "100%",
    height: "50%",
    zIndex: 2,
    margin: 0,
  },
  space: {
    paddingBottom: 120,
  },
});
